name: Haha

inputs:
  solutionPath:
    description: The path to the solution
    required: true
    type: string

outputs:
  releasePath:
    value: ${{ runs.steps.invokeFile.releasePath }}

runs:
  using: "composite"
  steps:
    - name: Write path as output
      shell: powershell
      run: Write-Output ${{inputs.solutionPath}}
    - name: File invokation
      id: invokeFile
      shell: powershell
      run: |
        $releasePath = ${{ github.action_path }}.\bin\haha.ps1
        Write-Output "::set-output name=releasePath::$releasePath"
        Write-Output "The output is: $releasePath"
      env:
        solutionPath: ${{inputs.solutionPath}}