name: Haha

inputs:
  solutionPath:
    description: The path to the solution
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Write path as output
      shell: powershell
      run: Write-Output ${{inputs.solutionPath}}
    - name: File invokation
      shell: cmd
      run: |
        .\bin\haha.ps1
      env:
        solutionPath: ${{inputs.solutionPath}}