name: Haha

inputs:
  solutionPath:
    description: The path to the solution
    required: true
    type: string
  targetPlatform:
    description: The platform the project should be built for (x64, x86, Win32)
    required: false
    type: string

outputs:
  releasePath:
    value: ${{ steps.invokeFile.outputs.releasePath }}

runs:
  using: "composite"
  steps:
    - name: Write secret and repo name
      shell: powershell
      run: |
        Write-Host $env:asdsecret
        Write-Host ${{github.repository}}
      env:
        asdsecret: ${{secrets.asdsecret}}
    - name: Write path as output
      shell: powershell
      run: Write-Output ${{inputs.solutionPath}}
    - name: File invokation
      id: invokeFile
      shell: powershell
      run: |
        ${{ github.action_path }}\bin\haha.ps1
      env:
        solutionPath: ${{ inputs.solutionPath }}
        platform: ${{ inputs.targetPlatform }}
    - name: Using output from previous script
      shell: powershell
      run: ${{ github.action_path }}\bin\second.ps1 "${{steps.invokeFile.outputs.releasePath}}"