name: Haha

inputs:
  solutionPath:
    description: The path to the solution
    required: true
    type: string
  targetPlatform:
    description: The platform the project should be built for (x64, x86, Win32)
    required: false
    type: string

outputs:
  releasePath:
    value: ${{ steps.invokeFile.outputs.releasePath }}

runs:
  using: "composite"
  steps:
    - name: Write path as output
      shell: powershell
      run: Write-Output ${{inputs.solutionPath}}
    - name: File invokation
      id: invokeFile
      shell: powershell
      run: |
        $releasePath = ${{ github.action_path }}.\bin\haha.ps1
        Write-Output "releasePath::$releasePath" >> $env:GITHUB_OUTPUT
        Write-Output "The output is: $releasePath"
      env:
        solutionPath: ${{ inputs.solutionPath }}
        platform: ${{ inputs.targetPlatform }}